Repository DXgovernance/dxvote, pull requests merged in 2021-12, with the labels that each got.

#432 feat: Add wallet and network switching to guilds.
  src/GuildsApp.tsx
  src/components/Guilds/Header/NetworkButton.tsx
  src/components/Guilds/Header/WalletButton.tsx
  src/components/Guilds/Header/index.tsx
Labels: Enhancement

#439 Additional Parameters added to status filter
  .gitignore
  src/cache/index.ts
  src/components/Proposal/Status/index.tsx
  src/components/Proposal/Votes/index.tsx
  src/hooks/useABIService.ts
  src/hooks/useEtherscanService.ts
  src/hooks/useFilteredProposals.ts
  src/pages/Forum.tsx
  src/pages/ProposalSubmission/Custom.tsx
  src/pages/proposals/index.tsx
  src/provider/connectors.ts
  src/serviceWorker.ts
  src/services/CoingeckoService.ts
  src/services/EventsService.ts
  src/services/PinataService.ts
  src/stores/DaoStore.ts
  src/utils/enums.ts
Labels: Bug

#449 Feature/guilds ENS address component
  package.json
  src/GuildsApp.tsx
  src/abis/ENSPublicResolver.json
  src/abis/ENSRegistrar.json
  src/abis/ERC1155.json
  src/abis/ERC721.json
  src/components/Guilds/Avatar/index.tsx
  src/components/Guilds/Header/NetworkButton.tsx
  src/components/Guilds/Header/WalletButton.tsx
  src/components/Guilds/ProposalActionsCard/ActionItem.tsx
  src/components/Guilds/common/Button/Button.tsx
  src/components/Guilds/common/Button/IconButton.tsx
  src/constants/addresses.ts
  src/hooks/Guilds/contracts/useContract.ts
  src/hooks/Guilds/ens/useENS.ts
  src/hooks/Guilds/ens/useENSAddress.ts
  src/hooks/Guilds/ens/useENSAvatar.ts
  src/hooks/Guilds/ens/useENSName.ts
  src/hooks/Guilds/ens/useENSRegistrar.ts
  src/hooks/Guilds/ens/useENSResolver.ts
  src/hooks/Guilds/nft/useERC1155NFT.ts
  src/hooks/Guilds/nft/useERC721NFT.ts
  src/pages/Guilds/Proposal.tsx
  src/services/ENSService.ts
  src/utils/address.ts
  src/utils/contracts.ts
  src/utils/url.ts
  yarn.lock
Labels: Enhancement

#474 fix: Remove hardcoded avatar address.
  src/components/Guilds/Header/WalletButton.tsx
Labels: Bug

#460 Feature/toast error
  package.json
  src/components/ErrorToast.tsx
  src/index.tsx
  yarn.lock
Labels: Enhancement, Good First Issue

#475 Feature/typechain
  .gitignore
  package.json
  src/components/Proposal/Calls/BaseCalls.tsx
  src/components/Proposal/Calls/EtherscanCalls.tsx
  src/components/Proposal/Calls/RecommendedCalls.tsx
  src/components/Proposal/Calls/index.tsx
  src/hooks/useABIService.ts
  src/provider/connectors.ts
  src/stores/DaoStore.ts
  src/types/types.d.ts
  src/utils/constants.ts
  tsconfig.json
  yarn.lock
Labels: Enhancement

#493 Feature/calculate worker proposal rep from mainnet
  src/hooks/useMainnetRep.ts
  src/pages/ProposalSubmission/ContributorProposal.tsx
Labels: Bug, Enhancement

#478 [WIP] Find proposal Ids of guild
  .prettierignore
  config-overrides.js
  hardhat.config.js
  package.json
  src/GuildsApp.tsx
  src/contracts/ERC20Guild.json
  src/hooks/Guilds/contracts/useContract.ts
  src/hooks/Guilds/useProposals.ts
  src/pages/Guilds/Guilds.tsx
  tsconfig.json
Labels: Enhancement, Guilds

#506 When switching network, DXvote loads mainnet proposals
  src/components/Proposals/ProposalsExporter.tsx
  src/contexts/proposals.tsx
  src/hooks/useFilterCriteria.ts
  src/hooks/useFilteredProposals.ts
  src/hooks/useProposals.ts
  src/index.tsx
  src/stores/DaoStore.ts
  src/types/types.d.ts
  src/utils/proposals.ts
Labels: Bug

#520 Feature/ens resolving optimizations
  src/hooks/Guilds/ens/useENS.ts
  src/hooks/Guilds/ens/useENSAddress.ts
  src/hooks/Guilds/ens/useENSAvatar.ts
  src/hooks/Guilds/ens/useENSName.ts
  src/hooks/Guilds/useLocalStorage.ts
  src/hooks/Guilds/useLocalStorageWithExpiry.ts
Labels: Enhancement

#507 Feature/improve guilds network management
  package.json
  src/GuildsApp.tsx
  src/components/Guilds/ErrorBoundary/GlobalErrorBoundary.tsx
  src/components/Guilds/Header/WalletButton.tsx
  src/components/Guilds/Header/index.tsx
  src/components/Guilds/Web3Manager/WalletWeb3Manager.tsx
  src/components/Guilds/Web3Modals/NetworkModal.tsx
  src/components/Guilds/Web3Modals/components/WalletInfoBox.tsx
  src/components/Header/index.tsx
  src/components/common/Button.tsx
  src/hooks/Guilds/ens/useENSAvatar.ts
  src/hooks/Guilds/ens/useENSRegistrar.ts
  src/hooks/Guilds/ens/useENSResolver.ts
  src/hooks/Guilds/useProposals.ts
  src/hooks/useParams.ts
  src/pages/Guilds/Guilds.tsx
  src/pages/Metadata.tsx
  yarn.lock
Labels: Bug, Enhancement, Guilds

#527 fix: Fixing executed proposal order
  src/hooks/useFilterCriteria.ts
  src/utils/proposals.ts
Labels: Bug

#524 Loading State for Guilds Proposals Page
  package.json
  src/components/Guilds/ProposalCard/index.tsx
  src/pages/Guilds/Guilds.tsx
  yarn.lock
Labels: Enhancement, Guilds
