Repository DXgovernance/dxvote, pull requests merged in 2021-09, with the labels that each got.

#118 Chore - Upgrade node engine to v14
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/deploy-ipfs.yml
  .github/workflows/deploy-netlify.yml
  .github/workflows/hash-build.yml
  package.json
Labels: Enhancement

#140 Added boolean check to convert from string to boolean
  src/pages/NewProposal.tsx
Labels: Bug

#153 Caching data using Cache API
  src/cache/index.ts
  src/pages/Configuration.tsx
  src/pages/NewProposal.tsx
  src/stores/BlockchainStore.ts
  src/utils/cache.ts
Labels: Enhancement

#146 Add Recommended Calls for DXvote Utils
  package-lock.json
  src/config.json
  src/contracts/DXDVestingFactory.json
  src/contracts/DXdaoNFT.json
  src/pages/NewProposal.tsx
  src/stores/ConfigStore.ts
  src/utils/cache.ts
  yarn.lock
Labels: Enhancement, Good First Issue

#158 Default should not show unboosted proposals
  src/config.json
  src/pages/Proposals.tsx
  src/utils/cache.ts
  yarn.lock
Labels: Enhancement

#160 Improve load times
  src/components/Web3ReactManager/index.tsx
  src/stores/BlockchainStore.ts
  src/utils/helperHooks.ts
Labels: Bug

#168 Take in count proposingRepReward for Redeems
  src/pages/Proposal.tsx
  src/stores/DaoStore.ts
  src/utils/proposals.ts
Labels: Bug

#169 PR Comments: Take in count proposingRepReward for Redeems
  src/stores/DaoStore.ts
  src/utils/proposals.ts
Labels: Bug

#181 Missed typo where positive votes were used for negative display
  src/pages/Proposal.tsx
Labels: Bug

#183 fix: Fixing string params for swapr farming campaign call
  src/config.json
Labels: Bug

#176 Proposals view style changes
  src/components/Footer/index.tsx
  src/index.css
  src/pages/Proposals.tsx
  src/theme/index.tsx
Labels: Enhancement
