Repository DXgovernance/dxvote, pull requests merged in 2021-11, with the labels that each got.

#270 Feature/contributor proposal creation page
  hardhat.config.js
  package-lock.json
  package.json
  scripts/buildCache.ts
  scripts/deployDevContracts.ts
  scripts/dev.sh
  src/components/LevelSelect/index.tsx
  src/components/Toggle.tsx
  src/configs/localhost/config.json
  src/configs/rinkeby/config.json
  src/configs/xdai/config.json
  src/hooks/useTokenService.ts
  src/index.tsx
  src/pages/Metadata.tsx
  src/pages/NewProposalType.tsx
  src/pages/ProposalSubmission/ContributorProposal.tsx
  src/pages/ProposalSubmission/Custom.tsx
  src/pages/SubmitProposal.tsx
  src/services/CoingeckoService.ts
  src/services/IPFSService.ts
  src/stores/ConfigStore.ts
  src/stores/DaoStore.ts
  src/types.d.ts
  src/utils/encodingCalls.ts
  src/utils/index.ts
  src/utils/number.ts
  yarn.lock
Labels: Enhancement

#324 feat: Adding user story prompt to new feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/to-do-task.md
Labels: Enhancement

#326 Fixing blockchain link in history
  src/components/common/BlockchainLink.tsx
  src/pages/Proposal.tsx
Labels: Bug

#339 feat: Override stablecoin amount in contributor proposals.
  src/pages/ProposalSubmission/ContributorProposal.tsx
Labels: Enhancement

#325 useProposals Hook
  src/hooks/useProposals.ts
Labels: Refactor

#338 fix: Tracking abis properly per file and getting local controller abi
  src/components/CallDataInformation.tsx
  src/hooks/useABIService.ts
  src/hooks/useEtherscanService.ts
  src/types.d.ts
Labels: Bug

#319 Feature/update cache without release
  package.json
  src/components/MainnetWeb3Manager/index.tsx
  src/components/Web3ReactManager/index.tsx
  src/contexts/index.ts
  src/index.tsx
  src/services/ENSService.ts
  src/services/IPFSService.ts
  src/stores/BlockchainStore.ts
  src/stores/ConfigStore.ts
  src/utils/constants.ts
Labels: Enhancement

#347 Improve DAOtalk importer UX.
  src/components/DiscourseImporter/index.tsx
  src/pages/Metadata.tsx
Labels: UI/UX Improvements

#336 Refactor Proposal into subcoments
  src/components/Proposal/Calls/CallDataInformation.tsx
  src/components/Proposal/Calls/index.tsx
  src/components/Proposal/Details/index.tsx
  src/components/Proposal/History/index.tsx
  src/components/Proposal/Stakes/index.tsx
  src/components/Proposal/Status/index.tsx
  src/components/Proposal/Votes/index.tsx
  src/components/Proposal/index.ts
  src/components/Proposal/styles.ts
  src/pages/Proposal.tsx
Labels: Refactor

#354 Fix/contributor bugs
  src/pages/ProposalSubmission/ContributorProposal.tsx
Labels: Bug

#360 Feature/blockchainlink component updates
  src/components/Web3ConnectStatus/index.tsx
  src/components/common/BlockchainLink.tsx
  src/pages/Configuration.tsx
  src/services/ENSService.ts
  src/utils/address.ts
Labels: Bug, Enhancement

#371 Feature/rep display component
  package.json
  src/components/Proposal/Calls/RecommendedCalls.tsx
  src/components/RepDisplay/index.tsx
  src/configs/xdai/config.json
  src/stores/ConfigStore.ts
  src/types.d.ts
  yarn.lock
Labels: Enhancement, UI/UX Improvements, Refactor

#365 feat: Adding date input to contributor proposal
  src/components/common/Forms/InputDate.tsx
  src/hooks/useTokenService.ts
  src/pages/ProposalSubmission/ContributorProposal.tsx
  src/stores/DaoStore.ts
Labels: Enhancement

#377 bugfix: Fix the Back to Proposals button.
  src/pages/ProposalSubmission/Custom.tsx
Labels: Bug

#344 Refactor Proposals Page
  src/components/Proposals/Search/SchemeSearch.tsx
  src/components/Proposals/Search/StatusSearch.tsx
  src/components/Proposals/Search/TitleSearch.tsx
  src/components/Proposals/Search/index.ts
  src/components/Proposals/Search/style.ts
  src/contexts/proposals.tsx
  src/hooks/useParams.ts
  src/hooks/useProposals.ts
  src/index.tsx
  src/pages/Proposals.tsx
  src/pages/proposals/index.tsx
  src/pages/proposals/styles.ts
  src/utils/proposals.ts
  tsconfig.json
Labels: Refactor

#361 Feature/guilds frontend setup
  public/index.html
  src/GuildsApp.tsx
  src/components/Guilds/Header/index.tsx
  src/components/Guilds/ProposalCard/index.tsx
  src/components/Guilds/Sidebar/index.tsx
  src/components/Guilds/common/Button/Button.tsx
  src/components/Guilds/common/Button/IconButton.tsx
  src/components/Guilds/common/Button/index.tsx
  src/components/Guilds/common/DropdownMenu/index.tsx
  src/components/Guilds/common/Layout/Box.tsx
  src/components/Guilds/common/Layout/Container.tsx
  src/components/Guilds/common/Layout/index.tsx
  src/components/Guilds/common/Menu/index.tsx
  src/index.css
  src/index.tsx
  src/pages/Guilds/Guilds.tsx
  src/theme/index.tsx
Labels: Enhancement

#379 fix: Changing value of input and removing bracket from string
  src/pages/ProposalSubmission/ContributorProposal.tsx
Labels: Bug

#388 feat: Add vesting contract creation to recommended calls for clear di…
  src/stores/ConfigStore.ts
Labels: Enhancement

#386 Feature/make cache ipfs hashes reproduceable
  defaultCacheFile.json
  scripts/buildCache.sh
  scripts/buildCache.ts
  src/cache/index.ts
  src/configs/arbitrum/config.json
  src/configs/arbitrumTestnet/config.json
  src/configs/mainnet/config.json
  src/configs/proposalTitles.json
  src/configs/rinkeby/config.json
  src/configs/xdai/config.json
  src/stores/BlockchainStore.ts
  src/stores/ConfigStore.ts
  src/stores/DaoStore.ts
Labels: Enhancement

#389 Refactor search and filtering
  src/components/Proposals/Search/SchemeSearch.tsx
  src/components/Proposals/Search/StatusSearch.tsx
  src/components/Proposals/Search/TitleSearch.tsx
  src/contexts/proposals.tsx
  src/hooks/useDebounceFn.ts
  src/hooks/useFilteredProposals.ts
  src/hooks/useMiniSearch.ts
  src/hooks/useQuery.ts
  src/hooks/useQueryStringValue.ts
  src/pages/proposals/index.tsx
Labels: Bug, Refactor

#391 Revert "Feature/250 ether input"
  package.json
  src/configs/localhost/config.json
  src/configs/proposalTitles.json
  src/pages/ProposalSubmission/Custom.tsx
  src/theme/index.tsx
  src/utils/yupSchemas.ts
  yarn.lock
Labels: Bug

#392 Feature/fix sorting executed
  src/utils/proposals.ts
Labels: Bug

#402 Feature/export data
  package.json
  src/components/FinanceInformation.tsx
  src/components/Proposals/ProposalsExporter.tsx
  src/components/common/Forms/InputDate.tsx
  src/contexts/proposals.tsx
  src/hooks/useExporters.ts
  src/hooks/useProposals.ts
  src/pages/User.tsx
  src/pages/proposals/index.tsx
  src/utils/array.ts
  yarn.lock
Labels: Enhancement

#406 Bug/search slow
  src/contexts/proposals.tsx
  src/hooks/useFilterCriteria.ts
  src/hooks/useFilteredProposals.ts
  src/hooks/useProposals.ts
  src/hooks/useRep.ts
  src/index.tsx
Labels: Bug

#404 feat: Added pokt urls and service
  src/components/Web3ReactManager/index.tsx
  src/components/common/BlockchainLink.tsx
  src/contexts/index.ts
  src/pages/Configuration.tsx
  src/provider/providerHooks.ts
  src/services/PoktService.ts
  src/utils/constants.ts
Labels: Enhancement

#421 feat: Adding param for vesting start date
  src/pages/ProposalSubmission/ContributorProposal.tsx
  src/utils/encodingCalls.ts
Labels: Enhancement

#420 Feature/guilds proposal page UI
  src/GuildsApp.tsx
  src/components/Guilds/ProposalActionsCard/ActionDetails.tsx
  src/components/Guilds/ProposalActionsCard/ActionItem.tsx
  src/components/Guilds/ProposalActionsCard/index.tsx
  src/components/Guilds/ProposalCard/index.tsx
  src/components/Guilds/ProposalSidebar/ProposalInfoCard/InfoItem.tsx
  src/components/Guilds/ProposalSidebar/ProposalInfoCard/index.tsx
  src/components/Guilds/ProposalSidebar/ProposalVoteCard/index.tsx
  src/components/Guilds/ProposalSidebar/index.tsx
  src/components/Guilds/ProposalStatus/index.tsx
  src/components/Guilds/SidebarCard/index.tsx
  src/components/Guilds/common/Button/Button.tsx
  src/components/Guilds/common/Layout/Box.tsx
  src/pages/Guilds/Proposal.tsx
Labels: Enhancement, UI/UX Improvements

#405 Handle eager-connect when switching networks.
  src/components/Web3ReactManager/index.tsx
  src/provider/providerHooks.ts
Labels: Bug, Enhancement

#419 feat: Adding environment variable for version from package json
  scripts/build.sh
  src/components/Footer/index.tsx
Labels: Enhancement

#422 Feature/guildcalls
  src/components/Guilds/ProposalActionsCard/ActionDetails.tsx
Labels: Enhancement, Guilds

#428 feat: Update (most of) the guilds components to use theme.
  src/GuildsApp.tsx
  src/components/Guilds/Header/index.tsx
  src/components/Guilds/ProposalActionsCard/ActionItem.tsx
  src/components/Guilds/ProposalActionsCard/index.tsx
  src/components/Guilds/ProposalCard/index.tsx
  src/components/Guilds/ProposalSidebar/ProposalInfoCard/InfoItem.tsx
  src/components/Guilds/ProposalSidebar/ProposalInfoCard/index.tsx
  src/components/Guilds/ProposalSidebar/ProposalVoteCard/index.tsx
  src/components/Guilds/ProposalStatus/index.tsx
  src/components/Guilds/Sidebar/index.tsx
  src/components/Guilds/SidebarCard/index.tsx
  src/components/Guilds/common/Button/Button.tsx
  src/components/Guilds/common/DropdownMenu/index.tsx
  src/components/Guilds/common/Form/index.tsx
  src/components/Guilds/common/Typography/Heading.tsx
  src/components/Guilds/common/Typography/index.tsx
  src/theme/GlobalTheme.ts
  src/theme/light.json
Labels: Enhancement, UI/UX Improvements
