Repository DXgovernance/dxvote, pull requests merged in 2022-01, with the labels that each got.

#552 feat: Added better representation of new permission recommended call
  src/components/Proposal/Calls/RecommendedCalls.tsx
  src/stores/ConfigStore.ts
Labels: Bug

#547 Feat/signed messages
  package.json
  src/components/ConfirmVoteModal/index.tsx
  src/components/Modal/index.tsx
  src/components/Proposal/Calls/EtherscanCalls.tsx
  src/components/Proposal/Calls/RecommendedCalls.tsx
  src/components/Proposal/Calls/index.tsx
  src/components/Proposal/History/index.tsx
  src/components/Proposal/Stakes/index.tsx
  src/components/Proposal/Votes/index.tsx
  src/components/Proposals/Search/StatusSearch.tsx
  src/contexts/index.ts
  src/pages/Proposal.tsx
  src/pages/proposals/index.tsx
  src/services/DaoService.ts
  src/services/IPFSService.ts
  src/services/MessageLoggerService.ts
  src/services/OrbitDBService.ts
  src/stores/Provider.ts
  src/utils/array.ts
  src/utils/cache.ts
  src/utils/index.ts
  src/utils/signature.ts
  src/utils/votes.ts
  yarn.lock
Labels: Enhancement

#558 Feature/proposal page data wireup
  package.json
  src/GuildsApp.tsx
  src/components/Guilds/AddressButton/index.tsx
  src/components/Guilds/Header/WalletButton.tsx
  src/components/Guilds/ProposalCard/index.tsx
  src/components/Guilds/ProposalStatus/index.tsx
  src/components/Guilds/common/UnstyledLink/index.tsx
  src/contexts/Guilds/proposals.tsx
  src/hooks/Guilds/ipfs/useIPFSFile.ts
  src/hooks/Guilds/ipfs/useIPFSNode.ts
  src/hooks/Guilds/proposals/usePaginatedProposals.ts
  src/hooks/Guilds/proposals/useProposal.ts
  src/hooks/Guilds/proposals/useProposals.ts
  src/pages/Guilds/Guilds.tsx
  src/pages/Guilds/Proposal.tsx
  src/types/types.guilds.d.ts
  src/utils/guildsProposals.ts
  yarn.lock
Labels: Enhancement, Guilds

#511 Transaction Modal
  src/GuildsApp.tsx
  src/components/Guilds/Sidebar/MemberActions.tsx
  src/components/Guilds/Web3Modals/TransactionModal.tsx
  src/components/Guilds/common/Button/Button.tsx
  src/components/Guilds/common/Layout/Box.tsx
  src/components/Guilds/common/Modal/index.tsx
Labels: Enhancement, Guilds

#576 feat: Add dxvote global error boundary.
  src/components/ErrorBoundary/GlobalErrorBoundary.tsx
  src/components/GlobalNotification/index.tsx
  src/index.tsx
  src/stores/BlockchainStore.ts
  src/theme/index.tsx
  src/utils/errors.ts
Labels: Enhancement

#590 Voting with less than full amount of REP shows an incorrect recap
  src/components/Proposal/Votes/index.tsx
Labels: Bug

#573 Quiet Ending Period Sorting Incorrectly
  src/hooks/useFilterCriteria.ts
Labels: Bug

#599 Bugfix/swr loading flash fixes
  src/components/Guilds/ProposalPage/ProposalActionsCard/ActionDetails.tsx
  src/components/Guilds/ProposalPage/ProposalActionsCard/ActionItem.tsx
  src/components/Guilds/ProposalPage/ProposalActionsCard/index.tsx
  src/components/Guilds/ProposalPage/ProposalDescription/index.tsx
  src/components/Guilds/ProposalPage/ProposalInfoCard/InfoItem.tsx
  src/components/Guilds/ProposalPage/ProposalInfoCard/index.tsx
  src/components/Guilds/ProposalPage/ProposalVoteCard/ProposalVotes.tsx
  src/components/Guilds/ProposalPage/ProposalVoteCard/index.tsx
  src/components/Guilds/ProposalPage/index.tsx
  src/components/Guilds/common/VotersButton/index.tsx
  src/hooks/Guilds/ipfs/useIPFSFile.ts
  src/pages/Guilds/Guilds.tsx
  src/pages/Guilds/Proposal.tsx
Labels: Bug, Enhancement, Guilds

#612 fix: Changing vote max to not round up
  src/components/Proposal/Votes/index.tsx
Labels: Bug

#575 Feature/proposal page sidebar data wireup
  src/GuildsApp.tsx
  src/components/Guilds/ProposalCard/ProposalCard.test.tsx
  src/components/Guilds/ProposalCard/index.tsx
  src/components/Guilds/ProposalPage/ProposalInfoCard/InfoItem.tsx
  src/components/Guilds/ProposalPage/ProposalInfoCard/index.tsx
  src/components/Guilds/ProposalPage/index.tsx
  src/components/Guilds/ProposalStatus/ProposalStatus.test.tsx
  src/components/Guilds/ProposalStatus/index.tsx
  src/components/Guilds/Sidebar/StakeTokens.tsx
  src/components/Guilds/Sidebar/index.tsx
  src/hooks/Guilds/ether-swr/middleware/logger.ts
  src/hooks/Guilds/ether-swr/useLockTime.ts
  src/hooks/Guilds/ether-swr/useProposal.ts
  src/hooks/Guilds/ether-swr/useTokenVault.ts
  src/hooks/Guilds/ether-swr/useTotalLocked.ts
  src/hooks/Guilds/ether-swr/useVoterLockTimestamp.ts
  src/hooks/Guilds/ether-swr/useVotingPowerForProposalCreation.ts
  src/hooks/Guilds/ether-swr/useVotingPowerForProposalExecution.ts
  src/hooks/Guilds/ether-swr/useVotingPowerOf.ts
  src/hooks/Guilds/index.ts
  src/hooks/Guilds/proposals/useProposal.ts
  src/hooks/Guilds/proposals/useProposals.ts
  src/hooks/Guilds/useProposal.ts
  src/types/types.guilds.d.ts
Labels: Enhancement, Guilds

#616 Feature/search by proposer address
  src/hooks/useFilteredProposals.ts
  src/services/ENSService.ts
Labels: Enhancement

#620 Feature/ether swr multi chain support
  src/components/Guilds/ProposalPage/ProposalDescription/index.tsx
  src/hooks/Guilds/ether-swr/useEtherSWR.ts
  src/hooks/Guilds/ether-swr/useGuildProposals.ts
  src/hooks/Guilds/ether-swr/useLockTime.ts
  src/hooks/Guilds/ether-swr/useProposal.ts
  src/hooks/Guilds/ether-swr/useTokenVault.ts
  src/hooks/Guilds/ether-swr/useTotalLocked.ts
  src/hooks/Guilds/ether-swr/useVoterLockTimestamp.ts
  src/hooks/Guilds/ether-swr/useVotingPowerForProposalCreation.ts
  src/hooks/Guilds/ether-swr/useVotingPowerForProposalExecution.ts
  src/hooks/Guilds/ether-swr/useVotingPowerOf.ts
  src/hooks/Guilds/useConfig.ts
  src/hooks/Guilds/usePrevious.ts
  src/pages/Guilds/Guilds.tsx
  src/pages/Guilds/Proposal.tsx
Labels: Bug, Enhancement

#597 New proposal type selection page
  scripts/build.sh
  src/GuildsApp.tsx
  src/assets/images/signal.svg
  src/assets/images/vector.svg
  src/components/Guilds/Filter/index.tsx
  src/components/Guilds/Header/index.tsx
  src/components/Guilds/ProposalTypes/index.tsx
  src/components/Guilds/Web3Modals/TransactionModal.tsx
  src/components/Guilds/common/Layout/Text.tsx
  src/components/Guilds/common/SVG/index.tsx
  src/configs/proposalTypes.tsx
Labels: Enhancement, Guilds

#617 Bugfix/guilds proposal card loading state fixes
  package.json
  src/components/Guilds/ProposalCard/ProposalCard.test.tsx
  src/components/Guilds/ProposalCard/index.tsx
  src/hooks/Guilds/ether-swr/useProposals.ts
  src/pages/Guilds/Guilds.tsx
  yarn.lock
Labels: Enhancement

#622 Feature/dxvote md preview improvements
  src/components/ProposalSubmission/Custom/Preview.tsx
  src/pages/FAQ.tsx
  src/pages/Metadata.tsx
  src/pages/Proposal.tsx
  src/pages/ProposalSubmission/Custom.tsx
Labels: Bug, Enhancement
